Home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

Login/urls.py
from django.urls import path
from . import views
from Login.views import UserLoginView, logout_user
from DosareMedicale.views import PetRecordCreateView, FormSuccessView


urlpatterns = [
    path('autentificare/', UserLoginView.as_view(), name='user_login'),
    path('dosare_medicale/', PetRecordCreateView.as_view(), name='dosare_medicale'),
    path('form_success/', FormSuccessView.as_view(), name='form_success'),
    path('deconectare/', views.logout_user, name='logout')
]

PetMedRegistry/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('user_login')),
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('Contact.urls')),
    path('', include('DespreNoi.urls')),
    path('', include('DosareMedicale.urls')),
    path('', include('Login.urls')),
    path('', include('Signin.urls')),
    path('', include('Search.urls')),
    path('reset-password/', include('ResetPassword.urls')),
]

Login/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(
        label='Email', 
        max_length=254,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
        error_messages={
            'required': 'Adresa de email este obligatorie.',
            'invalid': 'Adresa nu este valida.'
        }
    )
    password = forms.CharField(
        label='Parola', 
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        error_messages={
            'required': 'Introduceti o parola.',
        }    
    )

    remember_me = forms.BooleanField(required=False, label='Tine-ma minte')

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     if User.objects.filter(email=email.exists()):
    #         raise ValueError('Adresa este deja folosita')
    #     return email
    

Login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import CustomAuthenticationForm


class UserLoginView(LoginView):
    template_name = 'Login/login_page.html'
    authentication_form = CustomAuthenticationForm
    success_url = reverse_lazy('pet_record_list')

    def get_success_url(self):
        return self.success_url

    def form_valid(self, form):
        # Autentificăm utilizatorul folosind funcția authenticate() și login()
        email = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=email, password=password)
        remember_me = form.cleaned_data.get('remember_me')

        if user is not None:
            login(self.request, user)  # Autentificăm utilizatorul
            
            if remember_me:
                self.request.session.set_expiry(1209600) # Data de expirare dupa doua saptamani
            else:
                self.request.session.set_expiry(0)
            
            messages.success(self.request, 'Te-ai conectat cu succes!')
            return redirect(self.get_success_url())  # Redirecționăm utilizatorul
        
        else:
            messages.error(self.request, 'Adresa de email sau parola sunt incorecte!')
            return self.form_invalid(form)  # Dacă autentificarea nu a reușit, afișăm formularul invalid

    def form_invalid(self, form):
        # Când formularul este invalid, adăugăm mesaj de eroare
        messages.error(self.request, 'Te rugăm să introduci datele corecte!')
        return super().form_invalid(form)
    
def logout_user(request):
    logout(request)
    # messages.success(request, 'Te-ai deconectat cu succes!')
    return redirect('user_login')

templates/Login/login_page.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>PetMedRegistry</title>

        <!-- Fonturi și CSS -->
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,400;1,100&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <section>
            <div class="login-box">
                <!-- Formular de autentificare -->
                 {%block content%}
                <form method="post" action="{% url 'user_login' %}">
                    {% csrf_token %}
                    <h2>Autentificare</h2>

                    <!-- Câmp Email -->
                    <div class="input-box">
                        <span class="icon"><ion-icon name="mail"></ion-icon></span>
                        <input type="email" name="username"
                               class="{% if form.username.errors %} form-control is-invalid {% else %} form-control {% endif %}"
                               placeholder=""
                               value="{{ form.username.value|default:'' }}" id="email">
                        <label>Email</label>
                        {% if form.username.errors %}
                            <div class="error-message" id="email-error">
                                {% for error in form.username.errors %}
                                    <p>{{error}}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    {%endblock%}
                    <!-- Câmp Password -->
                    <div class="input-box">
                        <span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
                        <input type="password" name="password"
                                class="{% if form.password.errors %} form-control is-invalid {% else %} form-control {% endif %}"
                                placeholder="" id="password">
                        <label>Parola</label>
                        {% if form.password.errors %}
                            <div class="error-message" id="password-error">
                                {% for error in form.password.errors %}
                                    <p>{{error}}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>

                    <!-- Checkbox Remember Me și link Recuperare parolă -->
                    <div class="remember-forgot">
                        <label for="id_remember_me">
                            {{ form.remember_me }} Tine-ma minte
                        </label>
                        <a href="{% url 'password_reset' %}">Ai uitat parola?</a>
                    </div>

                    <!-- Buton de submit -->
                    <button type="submit" class="btn btn-primary w-100">Autentifica-te</button>

                    <!-- Link către înregistrare -->
                    <div class="register-link">
                        <p>Nu ai un cont? <a href="{% url 'signin_user' %}">  Inregistrare</a></p>
                    </div>
                </form>
            </div>
        </section>

        <!-- Scripturi pentru Ionicons -->
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
        <script>
            // Ascunde mesajele de eroare atunci când utilizatorul începe să editeze câmpul pentru email
            document.getElementById('email').addEventListener('focus', function() {
                var errorElement = document.getElementById('email-error');
                if (errorElement) {
                    errorElement.style.display = 'none';
                }
            });
        
            // Ascunde mesajele de eroare atunci când utilizatorul începe să editeze câmpul pentru parolă
            document.getElementById('password').addEventListener('focus', function() {
                var errorElement = document.getElementById('password-error');
                if (errorElement) {
                    errorElement.style.display = 'none';
                }
            });
        </script>
        
    </body>
</html>